# Github doesn't support YAML anchoring yet: https://github.community/t/support-for-yaml-anchors/16128
on:
  push:
    branches:
    - main
    - 'release/**'
    - dev

jobs:
  test-sponty:
    name: Test sponty-bot
    uses: ./.github/workflows/reusable-test-go.yaml
    with:
      component: .
  deploy-sponty:
    name: Deploy sponty-bot
    runs-on: ubuntu-latest
    environment: production
    env:
      SPONTY_GUILD_ID: ${{ secrets.SPONTY_GUILD_ID }}
      SPONTY_BOT_TOKEN: ${{ secrets.SPONTY_BOT_TOKEN }}
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Setting GUILD_ID secret
        run: flyctl secrets set GUILD_ID=$SPONTY_GUILD_ID
      - name: Setting BOT_TOKEN secret
        run: flyctl secrets set BOT_TOKEN=$SPONTY_BOT_TOKEN
      - name: Run flyctl deploy
        run: flyctl deploy --remote-only