# Github doesn't support YAML anchoring yet: https://github.community/t/support-for-yaml-anchors/16128
on:
  push:
    branches:
    - main
    - 'release/**'
    - dev

jobs:
  sponty:
    env:
      SPONTY_GUILD_ID: ${{ secrets.SPONTY_GUILD_ID }}
      SPONTY_BOT_TOKEN: ${{ secrets.SPONTY_BOT_TOKEN }}
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    jobs:
      set_secrets:
        name: Update secrets
        runs-on: ubuntu-latest
        steps:
          - run: flyctl secrets set GUILD_ID=$SPONTY_GUILD_ID
          - run: flyctl secrets set BOT_TOKEN=$SPONTY_BOT_TOKEN
      deploy:
        name: Deploy sponty-bot
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: superfly/flyctl-actions/setup-flyctl@master
          - run: flyctl deploy --remote-only