# Github doesn't support YAML anchoring yet: https://github.community/t/support-for-yaml-anchors/16128
on:
  pull_request:
    branches:
    - main
    - 'release/**'
    - dev

jobs:
  sponty:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run unit tests
        run: |
          # Going straight into running Docker build, since the build also includes running our
          # unit tests

          export IMAGE_NAME="${{ github.repository }}:${GITHUB_RUN_ID}_${GITHUB_RUN_ATTEMPT}"

          docker build -t ${IMAGE_NAME} .
