# Github doesn't support YAML anchoring yet: https://github.community/t/support-for-yaml-anchors/16128
on:
  pull_request:
    branches:
    - main
    - 'release/**'
    - dev

jobs:
  test-sponty:
    name: Test sponty-bot
    uses: ./.github/workflows/reusable-test-go.yaml
    with:
      component: .